name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./react-client

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: npm install and Run ui tests
        run: cd ./react-client && npm install && npm run test
        working-directory: ${{env.working-directory}}
      - name: Package cli application jar with Gradle
        run: ./gradlew shadowJar
      - name: Package web application jar with Gradle
        run: ./gradlew bootJar
      - name: Run validator on MBTA data
        run: java -jar application/cli-app/build/libs/gtfs-validator-v1.3.0-SNAPSHOT_cli.jar -u https://openmobilitydata.org/p/mbta/64/20200531/download -i input.zip -e input -o output -abort_on_error false -b false
      - name: Generate javadoc
        run: ./gradlew aggregateJavadocs
      - name: Persist cli jar
        uses: actions/upload-artifact@v2
        with:
          name: v1.3.0-SNAPSHOT_cli
          path: application/cli-app/build/libs/gtfs-validator-v1.3.0-SNAPSHOT_cli.jar
      - name: Persist web application jar
        uses: actions/upload-artifact@v2
        with:
          name: v1.3.0-SNAPSHOT_web
          path: application/spring-boot-app/build/libs/gtfs-validator-v1.3.0-SNAPSHOT_web.jar
      - name: Persist server test report
        uses: actions/upload-artifact@v2
        with:
          name: v1.3.0-SNAPSHOT_server_tests
          path: build/reports/allTests/
      - name: Persist react client test report
        uses: actions/upload-artifact@v2
        with:
          name: v1.3.0-SNAPSHOT_reactclient_tests
          path: react-client/test-reports/
      - name: Persist react client test coverage report
        uses: actions/upload-artifact@v2
        with:
          name: v1.3.0-SNAPSHOT_reactclient_tests
          path: react-client/coverage/
      - name: Persist javadoc
        uses: actions/upload-artifact@v2
        with:
          name: v1.3.0-SNAPSHOT_javadoc
          path: build/docs/javadoc/
